---
language: go

go:
  - 1.3
  - tip

install: 
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v -u github.com/tools/godep
  - godep get gopkg.in/check.v1
  - make build

script: 
  - godep go test -v
